### ISSUE TITLE
User should be a login

### ISSUE THREAD

**Issue by orlando** [debtcollective/header#2]
When a User clicks the Login Button, it should be redirected to the SSO provider and have an active session afterward.

## Acceptance criteria

- When a User clicks on **Log in**, It should create a session with the SSO provider and return to the application.

**Comment by duranmla** [comment]
I will close in favor of the following gif:

![http://recordit.co/gbg6Y7sgzT](http://recordit.co/gbg6Y7sgzT.gif)

_NOTICE: that the redirection has only worked for me in production, so I wasn't expected for this header to behave like that, as the video shows, it open the new tab but then the user needs to go manually back to the app_
