### ISSUE TITLE
User should be able to logout

### ISSUE THREAD

**Issue by orlando** [debtcollective/header#3]
When a User clicks the **Log out** Button, it should be redirected to the SSO provider and have an don't have a session afterward.

## Acceptance criteria

- When a User clicks on **Log out**, It should destroy the current session with the SSO provider and return to the application.

**Comment by duranmla** [comment]
(As done with issue #2 ) I will close in favor of the following gif:

![http://recordit.co/gbg6Y7sgzT](http://recordit.co/gbg6Y7sgzT.gif)

_NOTICE: that the redirection has only worked for me in production, so I wasn't expected for this header to behave like that, as the video shows, it open the new tab but then the user needs to go manually back to the app_

**Comment by duranmla** [comment]
I just realize that this feature is not in place yet, I will make a next PR including the fix for this. The video shows a logout from the Discourse app but we, of course, want to do it from the header as the previous component version does it.
