### ISSUE TITLE
User should be able to mark all notifications as Read

### ISSUE THREAD

**Issue by orlando** [debtcollective/header#5]
Discourse has the functionality to dismiss all notifications (Mark all notifications as Read). We want to have that same functionality in our Header. The action the user needs to click could look the same as twitch does

![image](https://user-images.githubusercontent.com/849872/53656409-ca27d300-3c18-11e9-81ca-5e19d4b8744e.png)

## Notes
Looks like Discourse uses the header Discourse-Clear-Notifications that is a comma-separated list of notifications IDs that need be marked as read.

https://github.com/discourse/discourse/blob/90ce44867595073d91ace4aacbb948f1e4f1ecb0/app/controllers/application_controller.rb#L292-L316

## Acceptance criteria

- Notifications should be marked as read when the user clicks **Mark All as Read** on the notifications dropdown.
- When you click on a notification, it should be marked as read the next time you visit the same site.

**Comment by duranmla** [comment]
I'm currently active on this Issue and I have "issues" trying to consume the Discourse API, basically, I have exposed my problem out to the community while I am also researching to see how to solve it.

https://meta.discourse.org/t/notifications-handling-from-api/113420

**Comment by duranmla** [comment]
Besides, worth to mention that the code mentioned on the description was actually introduced to allow the ability to mark notifications as read once the user "navigates" to a notification. Check https://github.com/discourse/discourse/commit/dd6ebde8247d849c1d429d5807c545f09091128d
