### ISSUE TITLE
Header displays user profile information when there's an active session

### ISSUE THREAD

**Issue by orlando** [debtcollective/header#9]
When the user has an active session, the header should display the user profile information in the header.

## Acceptance criteria

- With an active session, the header displays the user profile information.
- The user is able to go to its profile and user the links inside the profile menu.

**Comment by duranmla** [comment]
While the header currently shows and have access to the user info the links are not in place, I will also take the time to check a little bit about integration testing with this straight forward case.

**Comment by duranmla** [comment]
Closed by #15
